import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
/*
#################################################################

看來你想要維護程設班的網站
https://docusaurus.io/docs/sidebar
供你參考
                            by 14th 進階教學

#################################################################
*/
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [{type: 'autogenerated', dirName: '講義'}],
  introSidebar: [{type: 'autogenerated', dirName: 'intro'}],

  // But you can create a sidebar manually
/*   tutorialSidebar: [
    {
      type: 'category',
      label: '講義',
      dirName: '.',
      items: ['Beginner_textbook/Table'],
    },
  ], */
};

export default sidebars;
